// GENERATED by rotator-engine/sync-to-edge-function.js — do not hand-edit.
// Extracted verbatim from C:\Users\Daniel\Desktop\github\claude codebase\4 Sept\js\config.js by rotator-fixture/lib/extract.js.
export default {
  "STABLECOINS": {
    "tether": {
      "sym": "USDT",
      "apr": 4.5,
      "platform": "Aave / Compound"
    },
    "usd-coin": {
      "sym": "USDC",
      "apr": 4.2,
      "platform": "Aave / Compound"
    },
    "dai": {
      "sym": "DAI",
      "apr": 5,
      "platform": "Maker DSR"
    },
    "first-digital-usd": {
      "sym": "FDUSD",
      "apr": 3.8,
      "platform": "Binance Earn"
    },
    "true-usd": {
      "sym": "TUSD",
      "apr": 3.5,
      "platform": "Aave / Venus"
    },
    "ethena-usde": {
      "sym": "USDe",
      "apr": 12,
      "platform": "Ethena sUSDe"
    },
    "frax": {
      "sym": "FRAX",
      "apr": 4,
      "platform": "Frax Finance"
    },
    "paypal-usd": {
      "sym": "PYUSD",
      "apr": 3.2,
      "platform": "Aave / Morpho"
    },
    "gemini-dollar": {
      "sym": "GUSD",
      "apr": 3,
      "platform": "Gemini Earn"
    },
    "usdd": {
      "sym": "USDD",
      "apr": 5.5,
      "platform": "JustLend (Tron)"
    }
  },
  "TOKENOMICS_DB": {
    "bitcoin": {
      "deflation": "fixed",
      "unlockRisk": "low"
    },
    "ethereum": {
      "deflation": "partial",
      "unlockRisk": "low"
    },
    "binancecoin": {
      "deflation": "full",
      "unlockRisk": "low"
    },
    "solana": {
      "deflation": "none",
      "unlockRisk": "medium"
    },
    "ripple": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "dogecoin": {
      "deflation": "none",
      "unlockRisk": "low"
    },
    "cardano": {
      "deflation": "none",
      "unlockRisk": "low"
    },
    "avalanche-2": {
      "deflation": "partial",
      "unlockRisk": "medium"
    },
    "shiba-inu": {
      "deflation": "partial",
      "unlockRisk": "low"
    },
    "chainlink": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "polkadot": {
      "deflation": "none",
      "unlockRisk": "medium"
    },
    "bitcoin-cash": {
      "deflation": "fixed",
      "unlockRisk": "low"
    },
    "near": {
      "deflation": "none",
      "unlockRisk": "medium"
    },
    "litecoin": {
      "deflation": "fixed",
      "unlockRisk": "low"
    },
    "uniswap": {
      "deflation": "partial",
      "unlockRisk": "medium"
    },
    "internet-computer": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "ethereum-classic": {
      "deflation": "fixed",
      "unlockRisk": "low"
    },
    "stellar": {
      "deflation": "partial",
      "unlockRisk": "medium"
    },
    "monero": {
      "deflation": "none",
      "unlockRisk": "low"
    },
    "okb": {
      "deflation": "full",
      "unlockRisk": "low"
    },
    "hedera-hashgraph": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "filecoin": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "cosmos": {
      "deflation": "none",
      "unlockRisk": "medium"
    },
    "vechain": {
      "deflation": "partial",
      "unlockRisk": "low"
    },
    "tron": {
      "deflation": "partial",
      "unlockRisk": "low"
    },
    "sui": {
      "deflation": "none",
      "unlockRisk": "high",
      "unlock30d": 6.8
    },
    "aptos": {
      "deflation": "none",
      "unlockRisk": "high",
      "unlock30d": 5.9
    },
    "sei-network": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "render-token": {
      "deflation": "partial",
      "unlockRisk": "medium",
      "unlock30d": 3.2
    },
    "jupiter-exchange-solana": {
      "deflation": "partial",
      "unlockRisk": "medium"
    },
    "aave": {
      "deflation": "partial",
      "unlockRisk": "low"
    },
    "the-graph": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "curve-dao-token": {
      "deflation": "partial",
      "unlockRisk": "medium"
    },
    "maker": {
      "deflation": "full",
      "unlockRisk": "low"
    },
    "lido-dao": {
      "deflation": "none",
      "unlockRisk": "medium"
    },
    "arbitrum": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "optimism": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "stacks": {
      "deflation": "fixed",
      "unlockRisk": "medium"
    },
    "immutable-x": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "injective-protocol": {
      "deflation": "full",
      "unlockRisk": "low"
    },
    "blur": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "bonk": {
      "deflation": "partial",
      "unlockRisk": "low"
    },
    "dogwifcoin": {
      "deflation": "none",
      "unlockRisk": "low"
    },
    "book-of-meme": {
      "deflation": "none",
      "unlockRisk": "low"
    },
    "pepe": {
      "deflation": "none",
      "unlockRisk": "low"
    },
    "ondo-finance": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "worldcoin-wld": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "pyth-network": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "jito-governance-token": {
      "deflation": "none",
      "unlockRisk": "high"
    },
    "ethena": {
      "deflation": "partial",
      "unlockRisk": "high"
    }
  }
};
